### ISSUE TITLE
Frequent Server connection issues in local LAN

### ISSUE THREAD

**Issue by workflowsguy** [owncloud/ios#1102]
### Steps to reproduce
1. Open onwcloud client and pull down screen to refresh

### Expected behaviour
Data should be synced to/from server.

### Actual behaviour
Message "Connection to Server currently not possible" and "Timeout connecting to server" appear.
I am 40 cm away from my router and ownCloud server while testing this. Other iOS software and syncing methods (e.g. WebDAV) work correctly.
Previous ownCloud client version did not have this connection problem.

### Server configuration
**Web server:**
Apache (?)
**Database:**
MariaDB 5.5.57
**PHP version:**
5.6.38
**ownCloud version:**
9.1.8 (stable)
**Storage backend (external storage):**

### Client
**iOS version:**
12.1.4
**ownCloud app version:**
3.8.1 (0babef0a)
**Device model:**
iPhone 6s Plus
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by michaelstingl** [comment]
@workflowsguy This ownCloud iOS app is deprecated. The ownCloud team started to write a new one from scratch. Could you perform a quick check with the latest TestFlight beta? Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/

New iOS app has an awesome logging feature:
https://github.com/owncloud/ios-app/blob/master/doc/TROUBLESHOOTING.md

In case this issue is also present in the new app, please open a new issue in the new repo:
https://github.com/owncloud/ios-app/issues
