### ISSUE TITLE
ownCloud for iOS - add i-button to files to show file details

### ISSUE THREAD

**Issue by j-ed** [owncloud/ios#129]
Environment:
- ownCloud for iOS v3.0.0
- iOS 7.0.3

It is currently not possible to display file details in the ownCloud app, like the creation date, modification date, file owner etc. It would be a good idea to show an i-button behind every file name to access this kind of information.

**Comment by rperezb** [comment]
In order to be possible to read the full name, we have though that the solution is to include the file/folder full name in the more menu.
The file/folder name will be the first item shown.
The font size is expected to be slightly smaller than the size use for the other options (rename, move...)

![long file names](https://cloud.githubusercontent.com/assets/1846927/9489105/d2a2f8f8-4bde-11e5-8954-1549ef425e94.PNG)
related to https://github.com/owncloud/android/issues/559

**Comment by cdamken** [comment]
@felixboehm @bboule  No resolves-blue-ticket label here

**Comment by ggdiez** [comment]
And this is the result in the iOS app. Coming in the next version!!! ;)

![support for long names](https://cloud.githubusercontent.com/assets/2051473/9545208/9de49b30-4d87-11e5-824d-bc03f69f489e.png)

Here is the commit: https://github.com/owncloud/ios/commit/b82583b88fcfcce679d1baa2ed27b5fbbfa718c1

**Comment by rperezb** [comment]
This is likely to be a long enough name, it looks great!

**Comment by cdamken** [comment]
@rperezb In which version will be available?

@karlitschek Could you add the label "resolves-blue-ticket" in ios repository

**Comment by karlitschek** [comment]
@cdamken done

**Comment by rperezb** [comment]
@cdamken the idea is to release it next iOS version, 3.4.5
On Android, this is not expected for the moment.

**Comment by cdamken** [comment]
@karlitschek Thanks.

@rperezb Could you put it in a Milestone please?

**Comment by rperezb** [comment]
Done via https://github.com/owncloud/ios/pull/471

**Comment by cdamken** [comment]
Thanks All :+1:

**Comment by j-ed** [comment]
:+1:
