### ISSUE TITLE
Failure to authenticate with server using self-signed cert

### ISSUE THREAD

**Issue by meuterei11** [owncloud/ios#194]
I have an iPhone running iOS 7.1.1 with the owncloud app version 3.1.3 and server version 6.0.3-0. When I try to connect with my iPhone, I enter the server url, get prompted to confirm that I trust the server's certificate as its authenticity cannot be verified, confirm, and get prompted again; this repeated ad infinitum. On the console I receive the following message:

Owncloud iOs Client[11796] <Warning>:  SecKeyCreate init RSAPublicKey key: -50
Owncloud iOs Client[11796] <Warning>:  SecKeyCreate init RSAPublicKey key: -50
Owncloud iOs Client[11796] <Warning>: CFNetwork SSLHandshake failed (-9808)
Owncloud iOs Client[11796] <Warning>: NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9808)

**Comment by rperezb** [comment]
@javiergonzper may this be fixed within your work on: https://github.com/owncloud/ios/tree/show_possibility_accept_cert_after_change

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. Could you perform a quick check with the latest TestFlight beta? Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/

New iOS app has an awesome logging feature:
https://github.com/owncloud/ios-app/blob/master/doc/TROUBLESHOOTING.md

In case this issue is also present in the new app, please open a new issue in the new repo:
https://github.com/owncloud/ios-app/issues
