### ISSUE TITLE
Authentication error when plain HTTP is disabled

### ISSUE THREAD

**Issue by gavv** [owncloud/ios#214]
My web server (nginx) is configured to redirect all http to https (using 302 return code).

Web interface and linux client work good, but iOS app prints error when it tests server url:

```
Can not authenticate against this server
```

It seems that it tries to get `remote.php/webdav/` without username and password.

```
access.log

172.17.0.51 - - [13/Aug/2014:09:33:16 +0000] "GET /owncloud/status.php HTTP/1.0" 200 77 "-" "Owncloud%20iOs%20Client/3.2.0 CFNetwork/672.1.15 Darwin/14.0.0"
172.17.0.51 - - [13/Aug/2014:09:33:17 +0000] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.0" 401 285 "-" "Owncloud iOs Client/3.2.0 (iPhone; iOS 7.1.2; Scale/2.00)"
```

```
owncloud.log

{"reqId":"53eb09e855453","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: Username or password does not match","level":0,"time":"2014-08-13T06:47:04+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
```

After allowing http in nginx and using `http://` in server url, iOS app prints `Connection established` and works good. But I guess in this case iOS app will not use https at all?

During my expirements I also saw message `Secure connection established` instead of `Connection established`, but I can't reproduce it anymore.

So what is the proper way to use https with iOS app? Is plain http required?

**Comment by nasli** [comment]
Still happening?
If you are usin nginx, please check it https://forum.owncloud.org/viewtopic.php?f=24&t=9564&sid=bbe19b349bdda8fc903ca36538e407fa&start=10#p29119

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. Could you perform a quick check with the latest TestFlight beta? Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/

New iOS app has an awesome logging feature:
https://github.com/owncloud/ios-app/blob/master/doc/TROUBLESHOOTING.md

In case this issue is also present in the new app, please open a new issue in the new repo:
https://github.com/owncloud/ios-app/issues
