### ISSUE TITLE
iOS app crashes when viewing/opening large files

### ISSUE THREAD

**Issue by Steve06** [owncloud/ios#215]
For example, a large PDF file >100MB seems to be downloaded fully, but at the moment of viewing the app crashes. The file can also not be passed to/opened in another app like Adobe Reader or iBooks (from within the owncloud app).

**Comment by chirschberg** [comment]
Hi,

I have the same issue on an iPad iOS 8.1.2 using the actual owncloud app for iOS 3.3.2. But not only large PDF files are affected also smaller PDF-files with 7-8 MB can not be forwarded with the "open in ..." dialog. It takes 8-10 seconds until the dialog opens - the systems seems to freeze for a while. I am not sure what the app is processing.

The server is an owncloud 7.0.4 installation. But I think this is not the problem because I have the same behaviour, when switching the iPad to "Fly Mode" and all connections are offline.

Fixing this problem would be very helpful for me!

Regards,
Carsten

**Comment by Steve06** [comment]
Opening documents (PDF or Axcrypt-encrypted files with the Axcrypt app installed) from within owncloud ios 3.3.2 app does not seem to work at all anymore. I'm under the most recent ios 8.1.3. This has made owncloud useless for me, as I intended to use it to access important documents (encrypted with Axcrypt) while travelling.

When I click on the bottom left symbol to open a file, and then select an app like Adobe Reader or Axcrypt, there is no freeze or anything, it's just that nothing happens whatsoever.

This really needs to be resolved. I will be going back to Dropbox in the meantime.

**Comment by dashfield** [comment]
We're a high school of 1800 students, using OwnCloud as a primary method for delivering to and from iPads (since it can back-end onto our SMB server shares, etc). Our students access their text books in PDF format through OwnCloud, but are currently unable to get them due to this bug.
Every student has an iPad, mainly used as a method for accessing these text books.

We've had to start uploading text books to the webpages on the school intranet, which is causing all kinds of confusion.

I really hope this is addressed soon, as it is crippling our use of OwnCloud on iPads.

**Comment by rperezb** [comment]
@dashfield thanks for this report, we have started working on this (https://github.com/owncloud/ios/tree/crash_when_open_big_pdf_files)

**Comment by purigarcia** [comment]
This bug would be fixed soon, not the next the release but 3.4.1

**Comment by Steve06** [comment]
still not working on either of my ios 8.3 devices.

**Comment by javiergonzper** [comment]
@Steve06,  how big is the pdf? In order to try to reproduce it.

**Comment by Steve06** [comment]
It does not work with any file for me. I just tried a PDF only 620KB large. It does not work with epubs either which I'd like to open in ibooks. As I said, there's no crash or freeze, it's just that it doesn't happen. Doing the same from Dropbox works.

**Comment by javiergonzper** [comment]
It is strange we are very carefully when we release a new version to check that everything works after an update.
In this case we change how to open the files ("Open In") that is just code and should not be affected by an update.
