### ISSUE TITLE
InstantUpload: upload videos too

### ISSUE THREAD

**Issue by ariejan** [owncloud/ios#381]
It seems InstantUpload only uploads photos, not videos.
Can I help out with this in any way?

**Comment by javiergonzper** [comment]
Hello @ariejan,

Sure, you can!
But maybe first we should manage when the files have be upload (wifi or 3g) because right now the instant uploads are uploaded over any network. And the 3g consumption of a video upload could be dangerous.

**Comment by ariejan** [comment]
_dangerous_ as in :crocodile:? :-) 
Seriously, what can I do to help? For starters, the pile of issues is HUGE, I could help get that sorted out (before diving into any code and all that).

**Comment by javiergonzper** [comment]
Did you check the "junior jobs" ? Maybe it is not the best name because "junior" does not sound good but could be the best entry point to start to collaborate with us! :+1:

**Comment by rperezb** [comment]
hey @ariejan 
You are more than welcome to start contributing on the ownCloud project!

Before starting, we'd appreciate you sign the contribution agreement, http://owncloud.org/contribute/agreement/ and send it to @karlitschek 

You are right, there are several features to be implemented,  As @javiergonzper has suggested, just for an starting point so that you get to know the code, we'd suggested you to start with any of the issues labelled as junior job, what about? https://github.com/owncloud/ios/issues/239 this one is already implemented on the Android app and it would be great to have it too on the iOS :) 

You may be found useful to read https://github.com/owncloud/ios/blob/develop/CONTRIBUTING.md

In case you want to contact us not only we are on github but also on the IRC, freenode #owncloud-ios

**Comment by CrazyDymond88** [comment]
Hello!  I too would like this feature, but I don't really have any coding experience so I don't think I could help out any.  But adding this feature would make owncloud more of a direct alternative to dropbox (and of course much better!)

**Comment by enoch85** [comment]
+1 for this future. Just noticed what a big difference it is between the iOS app and the Andriod app as my wife just got an iPhone 6. Please prioritize this. Thank you.

**Comment by enoch85** [comment]
Please change milestone if not possible.

**Comment by enoch85** [comment]
Related #352

**Comment by rperezb** [comment]
@enoch85 sorry, this feature is not expected to be developed within this milestone, I move it to the backlog

**Comment by mbardelmeijer** [comment]
:+1:

**Comment by enoch85** [comment]
Any update here?

**Comment by rperezb** [comment]
Sorry, no changes ftm related to instant uploads

**Comment by enoch85** [comment]
Why is this in Backlog? Cryptocloud does it with the Nextcloud app.

**Comment by nasli** [comment]
Step by step @enoch85 :)
Within this release a lot of refactor have been made in instant uploads. 
Next step is to upload only with wifi option and then we will add to upload videos too

**Comment by enoch85** [comment]
@nasli sounds promising. :)

**Comment by rperezb** [comment]
let's close this one!
(if it were needed, please reopen)
