### ISSUE TITLE
Setting are lost everytime with InstantUpload On

### ISSUE THREAD

**Issue by onewaypub** [owncloud/ios#443]
Hi all,

since I switched on Instant upload the owncloud client for iOS start loosing all login settings and the URL. It seems this happens every time I took a picture which will be uploaded, but I'm not sure with that.

Also I recordnized, that after adding the connection settings again, the accounts will be duplicated. See attachement. I anonymized the user and the url, but they are all the same.

![photo-2015-08-13-12-12-11_1820](https://cloud.githubusercontent.com/assets/3080663/9247691/888503de-41b5-11e5-8232-0da25efa558c.PNG)

**Comment by ggdiez** [comment]
Hi @onewaypub 

Thanks for the information. With that we can limit the user case. 

What is your iPhone and you iOS version?

This issue is related with a Apple keychain problem when the app try to access the credentials data. It's an iOS problem and we will expect that will be fixed in iOS 9. 

Instead of enter again the login data the workaround is kill the app and open again. :(

It related with this #344

**Comment by onewaypub** [comment]
Phone 5s. iOS 8.4.1

Okay. Thanks for the workaround. :o)

**Comment by nasli** [comment]
As @ggdiez commented, let's track it on this previous one #344
