### ISSUE TITLE
Problem connecting to custom SSL port, self-signed and iOS client

### ISSUE THREAD

**Issue by jcaraba** [owncloud/ios#447]
Problem connecting to custom SSL port, self-signed and iOS client

Operating System:
Raspbian GNU/Linux 7

Apache Server Installed:
Server version: Apache/2.2.22 (Debian)

ownCloud Server Installed:
VersionString = '8.1.1'
Channel = 'stable'

iOS Device:
Version 8.4

iOS Client Installed:
Version 3.4.4

Custom port 55443 NAT'ed to Pi ownCloud Server

Can access ownCloud server via IE, Firefox, Chrome with no issues using ~https://personalhomeip.net:55443/owncloud~
Can access ownCloud server via ownCloud Windows desktop client using ~https://personalhomeip.net:55443/owncloud~
Cannot access ownCloud server via iOS client using ~https://personalhomeip.net:55443/owncloud~
    Error: Server Not Found

Verified self-Signed certificate is installed on iOS device and can access via mobile Safari and Chrome browsers.

remote.php/wedav accessible via web
status.php accessible via web

No other errors visible from iOS client.

~note: not real server address~

**Comment by javiergonzper** [comment]
Hello @jcaraba 
If you can access with the safari the app should also works. Contact us at apps@owncloud.com and give us a demo account to check it.

Thanks for report

**Comment by jcaraba** [comment]
Hello @javiergonzper 
I just updated all the configs to run on standard port 443 yesterday. I tested and can access ownCloud via all methods presented above. Please allow some time to revert changes back to 55443. I will contact with demo account via apps@owncloud.com.

Thank you.

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. Could you perform a quick check with the latest TestFlight beta? Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/

New iOS app has an awesome logging feature:
https://github.com/owncloud/ios-app/blob/master/doc/TROUBLESHOOTING.md

In case this issue is also present in the new app, please open a new issue in the new repo:
https://github.com/owncloud/ios-app/issues
