### ISSUE TITLE
App forgets login info in a few days

### ISSUE THREAD

**Issue by bisherbas** [owncloud/ios#455]
I enter my login info (server address, username, and password) again but now there are two of the same accounts shown in the Settings page. When I attempt to delete one, the app crashes and returns home screen. iPhone 5s latest iOs.

**Comment by ggdiez** [comment]
Hello @bisherbas 

This issue is related with a Apple keychain problem when the app try to access the credentials data. It's an iOS problem and we will expect that will be fixed in iOS 9.

Instead of enter again the login data the workaround is kill the app and open again. :(

We are talking about this here #344

**Comment by bisherbas** [comment]
Thanks @ggdiez! Appreciate the follow-up.
