### ISSUE TITLE
[3.4.5] Fullscreen view with Ipad and Owncloud iOS

### ISSUE THREAD

**Issue by sebhildebrandt** [owncloud/ios#501]
In previous versions I was able to see a full screen view of a doc (file/path structure slided to the left). Is this not longer possible or just a bug in version 3.4.5. This feature was extremely helpful!!

**Comment by rperezb** [comment]
@sebhildebrandt thanks for reporting this.

Yes, we are aware of this one, we plan to fix it within futuro ownCloud iOS versions.

This has been previously reported, let's follow its status on: https://github.com/owncloud/ios/issues/436

**Comment by sebhildebrandt** [comment]
Hopefully we mean the same thing ;-)
#436 is about "It is not possible to come back from full screen in iPad". 

What I mean, it is not even possible to go into full screen view of any doc (tap to see the pdf/video/image in full screen - this does NOT work). 
Regards

**Comment by rperezb** [comment]
yes :relaxed: we found it as a bug on the app due to the iOS9 version update, as I tried to say on the comment: https://github.com/owncloud/ios/issues/436#issuecomment-144983135 we have blocked the full mode in order to avoid that problem.
The plan is to fix it soon
WE do appreciate your interest on the app and your help!

**Comment by sebhildebrandt** [comment]
Perfect, thank you!!!
