### ISSUE TITLE
Upload new photos instantly without waiting for changes in location

### ISSUE THREAD

**Issue by enoch85** [owncloud/ios#511]
With the Android client the photo / video is uploaded in the background directly after it's taken. With the iOS client you manually have to open the app for this to happen. 

My suggestion is to make the uploads in the background instead, in the same way it's done on the Android client. 

Would that be possible?

**Comment by javiergonzper** [comment]
Hello @enoch85 
Until iOS 8 it was not possible but "now" (since one year ago) looks like it could be possible:
https://developer.apple.com/library/prerelease/ios//documentation/Photos/Reference/PHPhotoLibraryChangeObserver_Protocol/index.html#//apple_ref/occ/intf/PHPhotoLibraryChangeObserver

We are thinking in stop to give support to iOS7 so... maybe we can also include this functionality :+1: 
Thanks for your comment!

**Comment by enoch85** [comment]
ỲES PLEASE :)

**Comment by marinotws** [comment]
pardon the intrusion but PHPhotoLibraryChangeObserver do not work with app in background ...

**Comment by enoch85** [comment]
@marinotws Any suggestions?

**Comment by marinotws** [comment]
No, the current state of iOS does not allow any execution in background (the use of GPS is the only trick to awaken the app) ... we hope for the future.

**Comment by enoch85** [comment]
But how does Dropbox do it, or don't they upload in the background either?

**Comment by marinotws** [comment]
Dropbox use localization service (GPS) ... no one can bypass the restrictions of apple, Jailbreak excluse .....

**Comment by nasli** [comment]
With iOS OC app when a significant change in location is detected we check and uploaded new photos to your onwCloud app without need to open OC App.

 What Dropbox does is to use also changes in location and in that moment start to upload them but only in periods of 3 minutes time because they don't use background.

**Comment by marinotws** [comment]
"significant change in location" It is a bit sketchy, but when you change cell network (most common in the city much less in the suburbs) ;-)

**Comment by enoch85** [comment]
Are we talking 100 meters or 5 km? What is significant?

**Comment by nasli** [comment]
@enoch85, from apple doc "The significant-change location service delivers updates only when there has been a significant change in the device’s location, such as 500 meters or more."
but, as @marinotws commented, does not depend on distance, but you can try to force it turning on/off the airplane mode, or just open the app ;)

**Comment by enoch85** [comment]
@nasli 

> but you can try to force it turning on/off the airplane mode, or just open the app ;)

The reason I opened this issue is that I did not want to have to do that.

I will investigate this further and make som tests.

**Comment by nasli** [comment]
Thanks, any suggestion are welcome. ;)

**Comment by martva** [comment]
A suggestion as mentioned in #370 is implementing an Upload Now or Upload All photos button. That way we can turn off location services, because it is draining my battery faster than normal. 

This part is maybe in the wrong thread, but;
Another thing I noticed is that it seems that the owncloud client is making a local copy of the photo that needs to be uploaded. I had a nearly full iphone when I started uploading. It started off with ±300MB of free space. During the upload I got the message my phone was full. Looking at the space in use, It said 7MB. Why does the ios client seemingly make local copy of the file that's uploading?

**Comment by ggdiez** [comment]
Hello @martva, 

Because when we are uploading files in background we haven't access to the Photo Gallery. The app enter in background mode when are minimized for more than 3 minutes.

**Comment by enoch85** [comment]
@ggdiez Is the app activated via GPS when the "significant change in location" is reached? Otherwise there is no way around uploads in background as I see it.

**Comment by githubos1** [comment]
Would love to see that feature (automatic background upload to OC server) of photoalbum "taken pictures"  !!

Thank's 

Oliver

**Comment by ggdiez** [comment]
Yes @enoch85, the app is activated when the "significant change location" is reached, in that moment  we check and upload new photos to your onwCloud account without need to open OC App.

**Comment by marcus-no** [comment]
1) I like the photo library upload, but i would like the background part to be optional.
2) I would like the ios app to upload _all_ pictures, not only those taken after the installation of the ios app

**Comment by javiergonzper** [comment]
@marcus-no you are right, it should be optional in order to not upload while you do not want upload them.

**Comment by joshk03** [comment]
Currently location services is being used as a crude trigger to wake the app. The real issue is that it's married to all camera functionality. It's both or neither.  Let's separate them please. The suggestion made last year on #370 was excellent, we need two options...

1-photo uploads. (this enables camera functionality)
2-automatic wake. (this is the location hack, if you want it)

Here's why-

I had Dropbox:
I took pictures with my phone at home. When I was done I touched the Dropbox app, and my pictures greeted me on my laptop seconds later, ready for whatever came next. The app slept when not in use.

Now I have ownCloud:
I take pictures with my phone at home. When I'm done I click ownCloud but NOTHING HAPPENS. Even with location tracking ON the pics still don't upload because I am not moving. I then activate the upload manually anyway. The pictures finally greet me on my laptop seconds later. But then I drive to the store for printer paper, and ownCloud runs constantly, likely draining my battery because my phone is moving and ownCloud won't stay asleep. That's the problem. Work, play, all the time, it tracks my GPS.  And then there's the problem I just feel weird letting an app track my every move.

Please separate the options.

**Comment by joshk03** [comment]
Oh no... Yesterday when the stalker-warning popped up I agreed to banish owncloud from location services... I just discovered that none of my pictures taken since yesterday can ever be uploaded with ownlcloud... even after re-enabling location services.  There are so many pictures stuck on my phone...

**Comment by joshk03** [comment]
**Courts Just Said Turning Location Services On Is Like Telling Police They Can Search You**

Basic apps like Maps and Uber simply won't work without location services, and many people don't realize all that information is up for grabs without a warrant.
...
The 4th U.S. Circuit Court of Appeals in Richmond, Virginia, put out a ruling with sweeping implications: **Police can use months of cell phone location data obtained without a warrant simply by going to your service provider.**
...
Third-party doctrine: The third-party doctrine states that if you gave away a piece of information freely, the police can get it from whomever you gave it to — whether that's a bank, a business, a utility company or email server — without a warrant.
https://www.yahoo.com/news/courts-just-said-turning-location-172900568.html

**Comment by Jon-Schneider** [comment]
@joshk03 An update that enables foreground Instant Upload without Location Services being enabled is currently in progress (PR #681)

**Comment by joshk03** [comment]
@Jon-Schneider , Excellent.  When should I check back?  I ask because this topic was marked 'to develop' 7 months ago...  And I am very new here.

**Comment by Jon-Schneider** [comment]
@joshk03 My understanding is its scheduled to appear in the 3.5 release, which will probably happen in a month or two.

**Comment by joshk03** [comment]
Ok, thanks.

**Comment by typehassan** [comment]
Unsubscribe all threads

**Comment by enoch85** [comment]
Please remove milestone if not correct.

**Comment by Jon-Schneider** [comment]
The code is written, it just needs to undergo testing.

**Comment by nasli** [comment]
Let's keep tracking on the PR #681

**Comment by nasli** [comment]
Thanks to @Jon-Schneider this feature will be within next release
