### ISSUE TITLE
pdf downloads but does not show

### ISSUE THREAD

**Issue by hanscees** [owncloud/ios#546]
Hi,
I have ipad with client 3.4.6. Ios 9.1 (not updates to 9.2 yet because of mobile iron issues)
backend owncloud 8.1

I can download pdf files from the server. But then the screen stays white and no file is shown.
In previous versions I could see pdf's (but no fullscreen).
However now they do not show at all.

logging is like:

 [27/Dec/2015:19:47:04 +0000] "PROPFIND /remote.php/webdav/documents/bijen/Aandachtspunten%2520voor%2520bijenvriendelijk%2520beheer.pdf HTTP/1.1" 207 1641 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.4.6"
 [27/Dec/2015:19:47:04 +0000] "GET /remote.php/webdav/documents/bijen/Aandachtspunten%2520voor%2520bijenvriendelijk%2520beheer.pdf HTTP/1.1" 200 1551981 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.4.6"

**Comment by nasli** [comment]
Hello @hanscees, thanks for report it

We could not reproduce it here. 
For the logs seems to be a problem with the encoding, could you try with a file without any space?
How you download this file, by tap on it?
only happens with pdf files?
Thanks!

**Comment by hanscees** [comment]
Hi nasli,

I have this problem only when the owncloud server is not a virtual host but the default webserver (on apache).
the problem dissappears when the owncloud server is a virtual host so it seems. 


So I have an apache server which does not know its own name but serves owncloud as the basic webserver on say 192.168.3.4
I then resolve the dns name owncloud.somename.com to 192.168.3.4. Via bind or via a hostsfile.

In that scenario no files will download, but do not get displayed.
If I use another webdav client (webdavnav+) all works fine.

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. Could you perform a quick check with the latest TestFlight beta? Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/

New iOS app has an awesome logging feature:
https://github.com/owncloud/ios-app/blob/master/doc/TROUBLESHOOTING.md

In case this issue is also present in the new app, please open a new issue in the new repo:
https://github.com/owncloud/ios-app/issues
