### ISSUE TITLE
adapt app to iPad pro

### ISSUE THREAD

**Issue by rakekniven** [owncloud/ios#551]
App does not use full resolution of new iPad pro.
Menu on left looks to big.

**Comment by ggdiez** [comment]
Hello @rakekniven 

Thanks for reporting it.

Yes I have checked the app in an iPad pro and there are some images that need better resolution for the new big screen. We will try to include this fix in the next release. 

About the Menu, yes looks to big, but has the same proportions that in other iPads. Maybe we have to think in a different interface for the iPad pro in order to take advantage of the screen size.

**Comment by rakekniven** [comment]
Should I create another issue regarding size of menu?

**Comment by ggdiez** [comment]
It's not necessary I have included this issue in the milestone of the next release.

**Comment by rperezb** [comment]
done via: https://github.com/owncloud/ios/pull/582
