### ISSUE TITLE
Mention CalDAV/CardDAV address somewhere in the app

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/ios#555]
Same as for the Android app, so just linking that issue: https://github.com/owncloud/android/issues/1436

cc @rperezb @MTRichards (but let’s keep discussion on the Android issue maybe)

**Comment by DeepDiver1975** [comment]
On ios CardDAV and CalDAV are part of the OS - right?

We should add the accounts right away from the app - we have all information at hand and can setup the caldav and carddav accounts.

**Comment by jancborchardt** [comment]
Yep, CardDAV and CalDAV are part of iOS. @javiergonzper @ggdiez @nasli can you find out what is necessary to have the app automatically set this up?

**Comment by javiergonzper** [comment]
Hi @jancborchardt you can not modify the Settings options automatically from an app.
All the iOS environment work in closed sandboxes so you can not modify other "apps" from your app.
(a common example of this is when an app needs GPS. After the first installation Apple allows to the app to ask to have or not access to the Location Service but if the user said "NO" the app can not modify the Settings of option and needs that the user go to Settings -> Location Services and give the specific permission to the app). 

If anyone wants to add their caldav/cardav account must to go to Settings -> Mail, contacts, calendar. There is no other way.

**Comment by nasli** [comment]
Duplicated here #206

**Comment by DeepDiver1975** [comment]
> If anyone wants to add their caldav/cardav account must to go to Settings -> Mail, contacts, calendar. There is no other way.

What about at least displaying the information to the user?

**Comment by jancborchardt** [comment]
I’m closing https://github.com/owncloud/ios/issues/206 in favor of this one since it has more up to date info.

We need to display this information to people.

**Comment by DeepDiver1975** [comment]
Maybe we can check if the auto config profile is available on the server we connect to and display a message to the user so that the user can decide if he wants the profile to be applied?

**Comment by jancborchardt** [comment]
@nasli @javiergonzper @ggdiez comments about that? ^

**Comment by javiergonzper** [comment]
Uhm... for iOS looks like it could be possible:
https://www.fullcontact.com/blog/ios-configuration-profiles-carddav/ 

We should check if the format is correctly and that still working on iOS9

**Comment by aspdye** [comment]
Good call :+1: I want to add, that CardDAV and CalDAV should get independent configuration profiles, because some users may want to add only one of both - or are at least using one of those :grin:

**Comment by scolebrook** [comment]
Just pointing out that not every ownCloud instance has the Calendar and Contacts apps enabled. Many corporate environments will not use these apps because they have a different solution for managing these things, either a caldav/carddav/imap solution like Kerio Connect perhaps, or MS Exchange.

Trying to add configuration for calendars and contacts should only be available if the relevant app is enabled on the server. And should probably be a branding option that can be disabled entirely if an admin wants for whatever reason.

But for environments that use these apps I think having the ability for the client to automatically configure these services would be awesome. Kerio Connect actually offers an iOS profile on the login page for their web mail that includes config for caldav/carddav/imap so you basically have one tap setup. Something similar would be very cool.

Could also be something that is added to the first run wizard. Tap a link to download a profile. That might be easier to implement in a way that admins can control what is presented to users in their environment through a simple theme template.

**Comment by DeepDiver1975** [comment]
Theming Option sounds most reasonable

**Comment by jancborchardt** [comment]
Yep, simple branding option. CalDAV/CardDAV is in core so no reason to not show the address.

**Comment by michaelstingl** [comment]
contacts and calendar aren't in scope of the ownCloud iOS app
