### ISSUE TITLE
Can't switch storage provider using owncloud inside iOS Mail

### ISSUE THREAD

**Issue by patrickheinzelmann** [owncloud/ios#580]
Owncloud doesn't allow to switch the "Locations" when using it as storage provider inside of iOS Mail.

I'm using multiple cloud storage providers for different purposes (private & business).

While Dropbox, Creative Cloud and OneDrive allow to switch the "Locations" when adding an attachment to an email, Owncloud has only a cancel button and no button "Locations" to switch to another provider.

Owncloud should implement the common behaviour to support switching "Locations".

**Comment by mRoRo** [comment]
@patrickheinzelmann Thanks for your report. We will take it into account for next releases.

**Comment by jgoerzen** [comment]
Strangly, when I pull up this screen, I see for just a fraction of a second the more standard "locations" option on the titlebar, but then it is overwritten by OwnCloud (maybe because they want to show the logo?)  This is a pretty frustrating thing for anyone that needs to work with documents from multiple locations.

**Comment by nasli** [comment]
Please keep tracking here https://github.com/owncloud/ios/issues/920
