### ISSUE TITLE
Improve sharing: cancel -> switch back to other app

### ISSUE THREAD

**Issue by sronline** [owncloud/ios#587]
Sharing data between IOS apps and the OwnCloud app for uploading purposes should be improved:

- cancel in the upload dialogue should switch back to the application which has initiated the sharing

![owncloud_cancel](https://cloud.githubusercontent.com/assets/17158346/12953390/911b405a-d01a-11e5-88c4-a4fd4feb0b4a.png)

**Comment by sronline** [comment]
#386

**Comment by nasli** [comment]
@sronline Thanks for your feedback,

Since iOS9 it is possible to add a "back to previous app" button after a links was open from other app if our app support it,  but for previous version there is not public API for switching to another app, double-tap the home button for the same effect, or hit the home button once to go back to Springboard. 
Also with the share sheet extension it is allowed to come back as you can see on the following screenshot, but for this old way to share it is not possible.

![screenshot](https://cloud.githubusercontent.com/assets/6570505/14309456/dbdea1f2-fbdc-11e5-86ed-87fdc364c5d6.png)
