### ISSUE TITLE
MULTIPLE - SELECTION - As an OC user I want to be able to do the same action over more than 1 file/folder so that I don't have to repeat the same action several times

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#602]
AC:
- Related to: https://github.com/owncloud/android/pull/1176 and https://github.com/owncloud/android/issues/899
- Being able to select several files/folders
# How to access
- Under the current "..." button, include a new option called something such as: multi-select.
- When this option is selected, the user is on the "multi-selection mode" so that he may select as many files/folders as wanted. Buttons to select will be shown on the left side: https://cloud.githubusercontent.com/assets/6570505/13770690/1e9e9ade-ea89-11e5-9b21-bc9f4437d495.png
- As soon as the user has selected one item on the top left bar will appear the menu button "..."
- Under the menu button "..." it will be included the option:
  - Delete (for the moment, we will only include this option in future issues we will keep adding features, expected: move, favorite, unfavorite, download)
    +

-Once the user selects **delete** It will be offered the options to select which kind of deletion the user wants: locally or from server. This option 
- If a file is favorite, it can be only removed from the server side. Being favorites data selected, they won't be removed when the option is "locally"
- As soon as the user selects the option that he wants to take place, the option is started and the multiselect menu in closed
- Cancel button will be placed top bar right, by clicking on it, the multi-selection mode will be closed withouth doing any action

****\* This user stories is under definition process, ideas are welcome! ****

call for @owncloud/ios-developers @owncloud/designers @MTRichards @cmonteroluque 

## Final Design
 (As explained here https://github.com/owncloud/ios/issues/602#issuecomment-322184674)

- [ ] 1) Options tapping in "more" button:

![multi-selection 1](https://user-images.githubusercontent.com/2051473/29271836-c8774b94-80fd-11e7-9902-9eebbe752f6e.png)

- [ ] 2) After select "Select" option appear the "Edition" interface:

![multi-selection 2](https://user-images.githubusercontent.com/2051473/29271877-f8268c56-80fd-11e7-97ea-c528d1d511ef.png)

- [ ] 2.1 Checkbox selection. The user can select one or more items of the list.
 
2.2 Selection. The options button of the Navigation Bar changes to enable once the user has selected one item. 

![multi-selection 3](https://user-images.githubusercontent.com/2051473/29272018-821b7ea8-80fe-11e7-8f20-64664e517cc3.png)

- [ ] 3) Options. Once the user tap in "options" button, the options available for that selection appears.

![multi-selection 4](https://user-images.githubusercontent.com/2051473/29272024-87efc2c6-80fe-11e7-96a7-f8a04ceb4411.png)

The options "Available offline", "Download Files", "Delete" and "Rename" are direct action, the user taps and the action happens, maybe a pop up informative appear indicating the the action happened properly.

**Comment by nasli** [comment]
Another option is to add checkmarks as it is shown on the following image

![simulator screen shot 11 mar 2016 12 52 19](https://cloud.githubusercontent.com/assets/6570505/13701422/251e33fa-e788-11e5-8264-2578ff73cc5b.png)

**Comment by nasli** [comment]
Or with radio buttons:
![screen shot 2016-03-15 at 08 35 22](https://cloud.githubusercontent.com/assets/6570505/13770690/1e9e9ade-ea89-11e5-9b21-bc9f4437d495.png)

**Comment by rperezb** [comment]
I'd rather radio buttons besides it's aligned to Android implementation

How have you thought to enter in this mode?

@jancborchardt your input?

**Comment by mRoRo** [comment]
radio buttons +1

**Comment by javiergonzper** [comment]
Use radio buttons it is not native on the multi selection on iOS.
I do not recommend to change this behaviour.

**Comment by jesmrec** [comment]
Checkmarks are nicer (i mean :) )

**Comment by MTRichards** [comment]
@jancborchardt please weigh in on your opinion.

**Comment by cmonteroluque** [comment]
checkmarks seem more iOS-y to me, don't you think? It's a pretty similar implementation so I don't think it would be hard to figure out to users.

**Comment by MTRichards** [comment]
A new adjective, iOS-y :)
I personally agree with the checkmarks, I think it looks clean and more modern iOS-y as well. The circle check radio buttons look older iOS to me.

**Comment by mRoRo** [comment]
We should bear in mind that where checkmark is placed, we also show sharing icons. Maybe we could hide them or similar.

![simulator screen shot 28 mar 2016 10 23 46](https://cloud.githubusercontent.com/assets/15103194/14074507/cc9ff7ca-f4d1-11e5-8294-00ece0f24492.png)

**Comment by jancborchardt** [comment]
The check boxes on the left are definitely the better choice:

- they are more connected to the name of the file and the preview/icon
- it’s aligned with how we do it in the web interface (and in Android as well)
- it doesn’t interfere with the sharing icons on the right and any possible future 3-dot menu we might want to place there
- it’s done similarly in iOS Mail, Dropbox, Google Drive etc.


The checkmarks are way too invisible for this and it’s not entirely clear what they mean. It’s not immediately identifiable as multiselection.

**Comment by jancborchardt** [comment]
Oh and the 3-dot menu on the top right is great!

Then yep, the bar on the bottom with the actions. For now only delete, and then in the future we can have further actions there like favorite, move etc. (with icons ideally).

**Comment by Grimeton** [comment]
Hi,

Can we also add this feature to the sync list? Sometimes when I upload new pictures from my photos and I'm not sure if I uploaded them already, I upload them again. Then I get tons of sync errors where I have to check if I want to change the name, overwrite or delete them through a left swipe. When you have to delete 30 sync errors to make the red bubble at the bottom go away it's rather annoying todo it one by one and swipe to the left 30 times.

So it would either be nice the red bubble at the bottom disappears after looking into the sync list or to have an option to select multiple errors and mark them as read/delete them at once.

Thanks a lot!

KR,

Grimeton

**Comment by rperezb** [comment]
@Grimeton you are right, it's needed to have the option to remove all failed uploads at once.

However, this feature is slighly differente to the one within this issue, so let's open a new ticket for a better tracking

**Comment by cdamken** [comment]
> Sorry, but we need to drop issues from milestone 3.6.0 to get it out next to OC 10 server.

@davivel oC10 is now available, its it possible to add a milestone now?

**Comment by michaelstingl** [comment]
@cdamken [3.6.0](https://github.com/owncloud/ios/milestone/14) hasn't been released yet. So no milestone yet.

**Comment by michaelstingl** [comment]
Changing "Available offline" status should be possible for multiple selected files/folders.

**Comment by nasli** [comment]
Nearest to start to work on this, some design suggestions or mockups @ggdiez?

**Comment by ggdiez** [comment]
Hi, 

This is my proposal for this feature based in the new UI design #927 

I going to describe this design:

1) Options tapping in "more" button:

![multi-selection 1](https://user-images.githubusercontent.com/2051473/29271836-c8774b94-80fd-11e7-9902-9eebbe752f6e.png)

2) After select "Select" option appear the "Edition" interface:

![multi-selection 2](https://user-images.githubusercontent.com/2051473/29271877-f8268c56-80fd-11e7-97ea-c528d1d511ef.png)

2.1 Checkbox selection. The user can select one or more items of the list.
 
2.2 Selection. The options button of the Navigation Bar changes to enable once the user has selected one item. 

![multi-selection 3](https://user-images.githubusercontent.com/2051473/29272018-821b7ea8-80fe-11e7-8f20-64664e517cc3.png)

3) Options. Once the user tap in "options" button, the options available for that selection appears.

![multi-selection 4](https://user-images.githubusercontent.com/2051473/29272024-87efc2c6-80fe-11e7-96a7-f8a04ceb4411.png)

The options "Available offline", "Download Files", "Delete" and "Rename" are direct action, the user taps and the action happen, maybe a pop up informative appear indicating the the action happened properly.

4) Move and Copy

"Move" and "Copy" are different actions because needs a interface to select the destination of the selection. 

Each "Move" action will only have one destination and each "Copy" action will only have one destination like Android app. 

So "Move" and the "Copy" actions has the same interface changing "Move" word to "Copy". I'm going to show the Move action. 

Once the user taps in "Move" action the "Select destination" interface appear from below.

![multi-selection 5](https://user-images.githubusercontent.com/2051473/29272276-9ec8ed1e-80ff-11e7-8b24-e74ae6d565a9.png)

In this screen the user can see a list ordered first by folders and then by files, but the files will appear in a disabled mode. That it's only to indicate the user a reference of the current folder contain. 

In the subtitle of each folder will appear the folders that has inside,  if a folder has folders inside the depth arrow appear in enable mode indicating that the user can navigate inside the folder.

![multi-selection 6](https://user-images.githubusercontent.com/2051473/29272704-86b89312-8101-11e7-841c-efe0bdd6c04c.png)

The user only can select one option, and when select one option the "Move" button will change to enable mode. Until the user taps in "Move" option can change the selection. Once the user taps in "Move" the file/files will be moved to the destination. 

![multi-selection 7](https://user-images.githubusercontent.com/2051473/29272716-95e964ba-8101-11e7-80c0-51baaec8ddcf.png)

Here a video with an example of use:

https://owncloud.solidgear.es/index.php/s/Y5OuRFe0M5iG3gY

**Comment by michaelstingl** [comment]
@ggdiez Very cool!

**Comment by nasli** [comment]
Latest design updated in initial comment.

**Comment by michaelstingl** [comment]
This got implemented in the successor of this ownCloud app. You can test with the TestFlight beta.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
