### ISSUE TITLE
Ignore conflicting uploads

### ISSUE THREAD

**Issue by diehummel** [owncloud/ios#624]
Hello,

i miss the "ignore" button, when uploading files that already exist.
I just can chosse overwrite or rename.
Also on the "uploads" tab, i cannot delete/Cleanup the entries.

Would be fine do add some more usefull function in that way.

Or add an "sync phots and videos" option.
Currently i select teh photos in the ios photo app and share it to the ownCloud app. 
Instant upload worked just one time. (i didn't changed my location). And service location always on is not an option.

br
Christian

**Comment by rperezb** [comment]
@diehummel you have the option "cancel"  to postpone your decision about a conflict upload

On the uploads view, successfull uploads are limited to 30, they are shown the most recents ones, you are right, for the moment, it´s not possible to remove them manually. About the failed ones, you may either fix them by tapping on each one or cancel them taking advantage of the option shown once you do the gesture swipe over the failed one.
What it's not possible is to remove all at once, we plan to include it in future versions.

Instant uploads you may read about it on https://github.com/owncloud/ios/issues/370#issuecomment-121550822

In general, we'd rather one ticket per topic so that it's easier to track the status, thx

**Comment by rperezb** [comment]
closing since what you request is already included on other issues
