### ISSUE TITLE
iOS share File to App?

### ISSUE THREAD

**Issue by marbetschar** [owncloud/ios#625]
Sorry to post this here, but I'm unsure where to ask this and can't find any working solution on the web for it after hours of googling - and I've seen you where able to solve this already, so I'm hoping you can point me into the right direction.

I'm trying to implement a "share document" feature in my iOS app, but I'm only able to add my app under the "Open In..." Dialog - not in the primary selection list.

Your ownCloud app appears there - how did you add it there? Here's a screenshot from what I'm trying to explain:

![share](https://cloud.githubusercontent.com/assets/392542/14406565/cb3da5b0-feab-11e5-9503-91fd9d0174b8.png)

Sorry again for asking this here - but I'm absolutely lost :(

**Comment by javiergonzper** [comment]
Hello @marbetschar this is not the right place to ask things related with development. You should ask in Stackoverflow.
Anyway ownCloud appear there because we are using the **Share Extension** and maybe your app do not appear because you are using the old "Open With" mode.

http://www.imore.com/sharing-ios-8-explained
http://code.tutsplus.com/tutorials/ios-8-how-to-build-a-simple-action-extension--cms-22794

Good luck with your app.

**Comment by marbetschar** [comment]
@javiergonzper yeah you're right and I'm sorry for misuse - but I wasn't even able to figure out the right search term "Share Extension".

Thank you a bunch!!!!!
