### ISSUE TITLE
Feature Request: Use Realm Database

### ISSUE THREAD

**Issue by bkerensa** [owncloud/ios#628]
Realm database is faster and better performing than other databases on iOS and is
cross-platform which means OwnCloud for iOS could share an identical scheme
across both Android and iOS.

This would be a big performance win for your users.

**Comment by javiergonzper** [comment]
Hi @bkerensa 

Thank you for your feedback!
As far as I know realm still in "beta". I do not think so that add on ownCloud a library that still in beta it is a good idea.
Anyway, we are using FMDB creating the queries manually in order to have the best performance possible. On the tests that I made time ago the refresh of a folder with 5000 files are faster on the ownCloud iOS app than in Dropbox iOS app :sunglasses:. 

Migrate all the queries and the Database to Realm... would be a nightmare. And try to have the same DB scheme on iOS and Android after 4 years of development... :persevere:.

So... I think that it is better continue using FMDB 👍

**Comment by bkerensa** [comment]
@javiergonzper AFAIK Realm is not in Beta (and has not been for while) and major companies use it (Google, eBay, Cisco, DHS, McDonalds, Starbucks etc) 

That said if you ever reconsider Realm performs about 100% better than FMDB see screenshot showing benchmarks:
![screen shot 2016-04-17 at 11 26 38 pm](https://cloud.githubusercontent.com/assets/859175/14595431/fc4e80f4-04f3-11e6-8eca-564cda6a2de2.png)
![screen shot 2016-04-17 at 11 26 32 pm](https://cloud.githubusercontent.com/assets/859175/14595435/ff69ca00-04f3-11e6-9534-4fa14a499517.png)

**Comment by javiergonzper** [comment]
Hi @bkerensa 

I think that they still on beta. Check the version: https://realm.io/docs/objc/latest/ 0.98.8
Yes. Looks like it is faster. If we had to start again the project it is something that we should study but today in the point that we are migrate from FMDB to Realm... would be a nightmare. We have many tables, hundred of queries... really, it is something that we can not start at least today. Anyway contributions are welcome, if you think that realm is faster and you want to migrate the ownCloud app to Realm just do it 👍  and send the pull request (and have your branch updated because the development continue 😨 ).
