### ISSUE TITLE
Change the German translations to the formal speech 

### ISSUE THREAD

**Issue by rakekniven** [owncloud/ios#637]
For german we have to complete sets of strings at transifex.
One (de_DE) is for formal speech.
Other (de) one for informal speech.

The translations currently mixed up a little and I would volunteer to work on them.
Then I came to the question "How to select a given language?".

btw. currently the informal version is used on my iPhone running iOS 9.3.1
 
TASKS
- [X] Create branch "update_formal_german"
- [ ] Merge branch "update_formal_german"
- [x] Update iOS OC app to use de_DE @nasli
- [x] Add de_DE language in jenkins @DeepDiver1975 
- [ ] [QA] Validate

**Comment by rakekniven** [comment]
Should we just maintain just one version If no selection is possible?
If so which one? :confused:

**Comment by mRoRo** [comment]
@rakekniven thanks to contribute with your translations! 

The only German translations that are used in the iOS app are the ones that you can see in the "de" set. We don't use "de_DE" translations because this "informal" language is not supported by iOS. Have a look at your iOS Language & Region section. 

In order to be shown, the translations must be supported by iOS as well as included in the iOS app.

Sorry but the transifex link returns a 403 and we can't access the discussion.

**Comment by rakekniven** [comment]
The de_DE language it the formal one. See my first posting.
To view small transifex postings in german you have to log in first.

**Comment by rperezb** [comment]
ok, @rakekniven got it

We are using the informal german speech.
As you pointed out, giving the fact that we may only have 1 german translation on the iOS app, we will change if to the formal one within the next version.

thanks for pointing this out!

**Comment by nasli** [comment]
@DeepDiver1975 could you add "de_DE" language in jenkins? Thank you!
