### ISSUE TITLE
Photo functionality enhancement

### ISSUE THREAD

**Issue by joshk03** [owncloud/ios#644]
Currently location services is being used as a crude trigger to wake the app.  The real issue is that it's married to all camera functionality.  Let's separate it please.  I've read issue #370 that suggestion they made last year on #370 was excellent, we need two options...
1-photo uploads. (this enables camera functionality)
2-automatic wake. (this is the location hack, if you want it)

Here's why-

I had Dropbox:
I took pictures with my phone at home. When I was done I touched the Dropbox app, and my pictures greeted me on my laptop seconds later, ready for whatever came next.  The app slept when not in use.

Now I have ownCloud:
I take pictures with my phone at home. When I'm done I click ownCloud but NOTHING HAPPENS. Even with location tracking ON the pics still don't upload because I am not moving.  I then activate the upload manually anyway.  The pictures finally greet me on my laptop seconds later. But then I drive to the store for printer paper, and ownCloud runs constantly, draining my battery because my phone is moving and ownCloud won't sleep!  That's the problem.  Work, play, all the time, it tracks my GPS and won't sleep.
And then there's a different problem of I just feel weird letting an app track my every move.

Please separate the options.

**Comment by nasli** [comment]
Hi @joshk03,
instant uploads in ownCloud app should work whenever you open the app, not is necessary to change the location, but yes, right now it is necessary to allow check changes in location. 

You do not worry about battery drain, after 3 minutes without using the app enter in sleep mode and the only way to wake up it is checking the event of location that iOS provide us. When that significant change in location it is detected, if there are new photos they start to upload if not ,the app return sleep mode. No it is constantly checking your location, just when a big change in location it is detected we receive the notification. Your privacy it is assured, we do not track any location just use this notification.
 
Thanks for your feedback we will keep improving this feature!! Contributions are wellcome!!

Let's keep tracking this issue here #511
