### ISSUE TITLE
[FedShare] As an user I want to be able to enable/disable share option for federated shares in servers >=9.1

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#711]
AC:
- New share option will be added in the share edit privileges view for servers >= 9.1 
-By default share option will be enabled

-Related https://github.com/owncloud/core/issues/22122#issuecomment-228028647

TASKS
- [X] [GIT] Create branch "add_share_option_fed_share" @nasli
- [X] [GIT] Merge branch "add_share_option_fed_share" @mRoRo
- [X] [GIT] Create branch "add_share_option_fed_share_library" in library repo @nasli
- [X] [GIT] Merge branch "add_share_option_fed_share_library" into library repo @mRoRo
- [X] [DEV] Set constant version that will support edit share option @nasli
- [X] [DEV] Show share option @nasli
- [X] [DEV] Enable share option by default @nasli
- [X] [QA] Create test plan @jesmrec
- [X] [QA] Validate test plan @jesmrec @mcastroSG

PR:https://github.com/owncloud/ios/pull/729
PR: library https://github.com/owncloud/ios-library/pull/135

**Comment by nasli** [comment]
@jesmrec ready to test :)

**Comment by jesmrec** [comment]
### Bug

### Steps to reproduce

1. User1 shares a file with a user2 in another server granting share permission
2. User2 accepts the file and reshares it with User3, granting him/her to share
3. User1 revokes the share permission

### Actual behaviour

User2 can not disable the switch button "Can share" with the error "You are not allowed to share <file>"

### Expected behaviour

User2 can disable the switch button. If user2 would want to enable it again, he/she could not.

Device: iPadAir v8.1.2

Servers:
{"installed":true,"maintenance":false,"version":"9.1.0.11","versionstring":"9.1.0 RC1","edition":"Enterprise"}

**Comment by mcastroSG** [comment]
@nasli @mRoRo ready to merge.

**Comment by mRoRo** [comment]
@mcastroSG thanks. I'll review the code.
