### ISSUE TITLE
Here is Localizable.strings of zh-Hans.lproj ,has been translated to Chinese all

### ISSUE THREAD

**Issue by mossane** [owncloud/ios#798]
Chinese Localizable.strings
[zh-Hans.lproj.zip](https://github.com/owncloud/ios/files/546388/zh-Hans.lproj.zip)

other things:
replace k_path_instant_upload with NSLocalizedString(@"instant_updloads_section", nil)

constants.h
#define k_path_instant_upload @"InstantUpload"

InstantUpload.h
                    [app.prepareFiles addAssetsToUpload:newPhotos andRemoteFolder:[[NSString alloc] initWithFormat:@"%@%@/",[UtilsUrls getFullRemoteServerPathWithWebDav:ACTIVE_USER], NSLocalizedString(@"instant_updloads_section", nil) /*k_path_instant_upload*/]];

ManageUploadRequest.m

            if ([ManageAppSettingsDB isInstantUpload] && [folderInstantUpload isEqualToString:NSLocalizedString(@"instant_updloads_section", nil)/*k_path_instant_upload*/]) {
                //create folder instant upload
                [self newFolder:_currentUpload.destinyFolder];

**Comment by nasli** [comment]
Hi @mossane thanks for your contribution!

We use transifex to manage languages translations. We want to welcome you to our transifex community! Join us here  https://www.transifex.com/owncloud-org/owncloud/language/zh_CN/ and keep supporting this language. 

Related translatable instant upload folder, instead of that, we plan to allow the user to select the location. Keep tracking here #453
